#!/bin/sh

if [ $# -ne 2 ]; then
	
	if [ ! -f $1.m ]; then
		echo "close all;\nclear all;\n %Exercice n°$1" > $1.m
	else
		echo "Exercice $1 already exists: $1.m"
	fi
else
echo "Syntax: ./new <exercice-name>"
fi
